[project]
name = "cs430"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.6.0",
    "z3>=0.2.0",
    "z3-solver>=4.15.8.0",
]
